name: Pull Request Comment Workflow

on:
  pull_request:
    types: [opened, edited, synchronize]

jobs:
    pr-comment:
        runs-on: ubuntu-latest
        steps:
            - name: Comment on New PR
              id: comment
              uses: actions/github-script@v6
              with:
                script: |
                  github.rest.issues.createComment({
                    owner: context.repo.owner,
                    repo: context.repo.repo,
                    issue_number: context.issue.number,
                    body: `Hello @${context.payload.pull_request.user.login}, thanks for opening this PR!`
                  });
                  