name: Simple Action Workflow

on: [push]

jobs:
    checkout-action:
        runs-on: ubuntu-latest
        steps:
            - name: List of Files Before
              run: ls -a

            - name: Checkout Repository
              uses: actions/checkout@v2

            - name: List of Files After
              run: ls -a

    simple-action-workflow-test:
        runs-on: ubuntu-latest
        steps:
            - name: Simple JS Action
              id: greet
              uses: actions/hello-world-javascript-action@v1
              with:
                who-to-greet: 'Mona the Octocat'
            - name: Log Greeting Time
              run: echo "${{ steps.greet.outputs.greeting }} at ${{ steps.greet.outputs.time }}"
